databases:
  - name: trek-cameroon-db
    plan: free
    region: frankfurt
    postgresMajorVersion: "16"

services:
  - type: web
    name: trek-cameroon-backend
    env: node
    plan: free
    region: frankfurt
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npx prisma db push
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: trek-cameroon-db
          property: connectionString
      - key: CORS_ORIGIN
        value: https://trek-cameroon.vercel.app,http://localhost:3000
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: BCRYPT_ROUNDS
        value: "12"
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_FOLDER
        value: trek-cameroon
      - key: BOOKING_COMMISSION_PCT
        value: "12"
      - key: PHOTO_COMMISSION_PCT
        value: "20"
      - key: SEED_ADMIN_EMAIL
        value: admin@trekcameroon.cm
      - key: SEED_ADMIN_PASSWORD
        sync: false
